name: CI Automation Suite

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: QA
    env:
      RABBIT_PWD: ${{ secrets.RABBIT_PWD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build and Run Tests
        run: mvn clean test

      - name: Upload Customer-Availability Report
        uses: actions/upload-artifact@v2
        with:
          name: Customer-Availability-Report
          path: target/Customer-Availability.html
